# Generated by Django 3.1.7 on 2021-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20210408_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='outcome',
            field=models.CharField(default='negative', max_length=8),
        ),
    ]
