# Generated by Django 3.1.7 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20210408_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_with_confirmed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='test_indication',
            field=models.CharField(choices=[('test_indication_Abroad', 'Abroad'), ('test_indication_Contact with confirmed', 'Contact with confirmed'), ('test_indication_Other', 'Other')], default='test_indication_Other', max_length=50),
        ),
    ]
