# Generated by Django 3.1.7 on 2021-04-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, unique=True)),
                ('stage', models.CharField(default='1', max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(default='male', max_length=10)),
                ('cough', models.BooleanField(default=False)),
                ('breath_shortness', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('contact_with_confirmed', models.BooleanField(default=False)),
                ('outcome', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
